NumPy(Numerical Python) is a fundamental library for Python numerical computing. It provides efficient multi-dimensional array objects and various mathematical functions for handling large datasets making it a critical tool for professionals in fields that require heavy computation.

Key Features : N-Dimensional arrays, arrays with high performance, vectorization



# 1. CREATING ARRAYS

In [11]:
import numpy as np
arr = [1,2,3,4,5,6,7]
arr1 = np.array(arr)
arr2 = np.array([6,3,5,8,34,2,4,5,75])
arr2

array([ 6,  3,  5,  8, 34,  2,  4,  5, 75])

#### Zeros Array

In [12]:
# Zeros Array
arr1 = np.zeros(5)
arr2 = np.zeros(dtype=float, shape = 10)
arr3 = np.zeros(dtype=int, shape = (3,3))
arr4 = np.zeros(dtype=int, shape=(4,5), order='C')
arr5 = np.zeros(dtype=int, shape=(4,5), order='F')
print(arr4)
print(arr5)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Ones Array

In [13]:
# Ones array
arr1 = np.ones(5)
arr2 = np.ones((5,5))
arr3 = np.ones(dtype=int, shape=(3,4))
print(arr1)
print(arr2)
print(arr3)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#### Fill array with specific value

In [14]:
# fill array
arr = np.full((5,5),2)
arr = np.full(shape=(4,4),fill_value=11)
arr

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

#### Random Integers and values

In [15]:
# Random integers and random values
arr1 = np.random.rand(5)
arr2 = np.random.randint(2,100,(5,5))
print(arr1)
print(arr2)

[0.87059783 0.19169376 0.78677698 0.03000121 0.99425879]
[[47  9 54 21 57]
 [71 78 26  5 58]
 [41  7  7 84  9]
 [45 31 77 70 32]
 [ 6 46 57 44 57]]


#### Creating Array with values in a range

In [29]:
arr1 = np.arange(0,20,2)
arr2 = np.arange(0,20,4,dtype=float)
arr3 = np.linspace(0,1,num=10)
arr3= np.linspace(0,1,num=9,dtype=float)
arr3 = np.linspace(0,1,num=10,endpoint=False)
arr4,step = np.linspace(0,10,num=5, retstep=True)
arr4,step = np.linspace(0,1,num=10,retstep=True,endpoint=False)
step

np.float64(0.1)

#### Identity Matrix

In [30]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Diagonal Matrix

In [33]:
arr = np.diag([1,4,5])
arr

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

# 2. ARRAY MANIPULATION

#### Copy and view array

In [40]:
arr = np.arange(10,dtype='int16')
print(arr)
v = arr.view('int16')
print(arr)
v += 1
print(arr)

# copy array
arr = np.arange(0,10,2)
print(arr)
arr1 = arr.copy()
arr[0] = 1000
print(arr1)

print(id(arr))
print(id(arr1))


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[0 2 4 6 8]
[0 2 4 6 8]
2523285458928
2523285916720


#### Appending values to the end of array

In [46]:
# Appending single value to a 1d array
arr = np.array([1,3,5,7,9])
arr = np.append(arr,11)

# Appending another array to an array
arr = np.append(arr,[2,4,6,8])

# Appending values at the end using concatenation
arr1 = np.array([22,33,44,55,66])
arr1 = np.concatenate((arr,arr1),axis=0)
arr1

array([ 1,  3,  5,  7,  9, 11,  2,  4,  6,  8, 22, 33, 44, 55, 66])

#### Swapping Columns

In [ ]:
arr = np.arange(12).reshape(4,3)
arr[:,[2,0]] = arr[:,[0,2]]
arr

# Function to swap the columns
def Swap(arr, start_index, last_index):
    arr[:, [start_index, last_index]] = arr[:, [last_index, start_index]]



array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9]])

#### Horizontal stack and vertical stack

In [53]:
arr1 = np.array([[9,8,7,6],[1,2,3,4]])
arr2 = np.array([[5,6,7,8],[2,4,6,8]])
arr = np.hstack((arr1,arr2))
arr = np.vstack((arr1,arr2))

arr

array([[9, 8, 7, 6],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])